path: /data/PreprocessedData/MSTMap_new
train_subject: ['subject5', 'subject6', 'subject7', 'subject8', 'subject9', 'subject10', 'subject11', 'subject13', 'subject14', 'subject15', 'subject16']
valid_subject: ['subject17', 'subject18', 'subject19']
test_subject: ['subject1', 'subject2', 'subject3', 'subject4']
exclude_list: [
    'subject7_driving_small_motion_975',

    'subject7_driving_still_975',

    'subject2_garage_small_motion_940', 'subject6_garage_small_motion_975',

    'subject5_garage_still_975', 'subject6_garage_still_975',
]
selected_topic: []
step: 30