dataset:
  path: /data/PreprocessedData/MR-NIRP_final_raw/RGB
  train_subject: ['subject1', 'subject2', 'subject3', 'subject4', 'subject5', 'subject6', 'subject7', 'subject8', 'subject16', 'subject17', 'subject18', 'subject19']
  valid_subject: ['subject9', 'subject10', 'subject11']
  test_subject: ['subject13', 'subject14', 'subject15']
  exclude_list: [
      'subject7_driving_small_motion_975',

      'subject7_driving_still_975',

      'subject2_garage_small_motion_940', 'subject6_garage_small_motion_975',

      'subject5_garage_still_975', 'subject6_garage_still_975',
  ]
  selected_topic: []
  step: 30
  map_type: [CHROM_POS_G, YUV, NIR]

model:
  channels: 6
  num_classes: 224
  pretrained_path: 


runner:
  task: "train"
  name: "fold_5"
  batch_size: 64
  epochs: 20
  warm_epochs: 5
  lr: 0.001
  device: "cuda:0"
  weight_decay: 0.05
  layer_decay: 0.75